server:
  port: 8089
styz:
  browser:
    loginPage: /login
    loginSuccessPage: /index
  validate:
    imageCode:
      length: 100
      width: 30
      count: 4
      expire: 120
      linecount: 0
      includeUrls: /

mybatis:
  #  config-location: classpath:/mybatis.cfg.xml
  type-alias-package: com.styz.api.model
  mapper-locations:
    - classpath*:mapper/*Mapper.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://k8s-n1:3307/db2
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 10
      max-total: 20
      max-wait-millis: 10

  thymeleaf:
    suffix: .html
    cache: true
    mode: HTML
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
# 配置国际化消息
  messages:
    basename: i18n.login
logging:
  level:
    root: info



