mybatis:
  #  config-location: classpath:/mybatis.cfg.xml
  type-alias-package: com.styz.api.model
  mapper-locations:
    - classpath*:mapper/*Mapper.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://k8s-n1:3307/db2
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 10
      max-total: 20
      max-wait-millis: 10
  security:
    user:
      name: user
      password: user
server:
  port: 8085
security:
  basic:
    enabled: false

swagger:
  enable: true